yolo_model:

  config_file:
    name: yolov3-mapper.cfg
  weight_file:
    name: BEV-summer-179900.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - cone
      - bush
      - tree
      - UGV
