yolo_model:

  config_file:
    name: yolov3-obj-vis.cfg
  weight_file:
    name: yolov3-obj_111000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - cone
      - bush
      - tree
