yolo_model:

  config_file:
    name: yolov3-rover-and-cone-vis.cfg
  weight_file:
    name: rover-and-cone_416-anchor-obj4_last.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - cone
      - UGV
